version: '3'
# User-> apigw -> service1-> apigw -> service2 -> apigw -> service3 -> apigw -> httpbin.org
#
services:
    service1:
        image: mcheo/testhttpserverforward
        ports:
            - "8081:8080"
        command: apigw 81
        #service1 will forward request to next hop, apigw port 81
    service2:
        image: mcheo/testhttpserverforward
        ports:
            - "8082:8080"
        command: apigw 82
    service3:
        image: mcheo/testhttpserverforward
        ports:
            - "8083:8080" 
        command: apigw 83
    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
    apigw:
        image: opentracing/nginx-opentracing
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf.d/:/etc/nginx/conf.d/:ro
            - ./zipkin-config.json:/etc/zipkin/zipkin-config.json:ro
        depends_on:
            - service1
            - service2
            - service3

